name: Cache Rust wasm build
description: Cache Cargo build artifacts for the cli/wasm crate

runs:
  using: composite
  steps:
    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: rust-wasm-${{ runner.os }}-${{ hashFiles('Cargo.toml', 'cli/wasm/Cargo.toml', 'Cargo.lock', 'cli/wasm/src/**') }}
        restore-keys: |
          rust-wasm-${{ runner.os }}-
        path: target
