name: CLI bundle

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        node-version: [20, 22, 24]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}, node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.17
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install npm dependencies
        run: cd cli && npm i

      - name: Prepare
        run: cd cli && npm run prepare

      - name: Bundle
        run: cd cli && npm run bundle

      - name: Check local bundle
        run: node ./cli/bundle/cli.js -v

      - name: Install bundle globally
        run: npm i -g ./cli/bundle/cli.tgz

      - name: Check global bundle
        run: mops -v

      - run: mops format

  ci-ok-cli:
    if: always()
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
