name: Code quality

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: "npm"
      - name: Install
        run: |
          npm ci --ignore-scripts &
          (cd frontend && npm ci) &
          (cd cli && npm ci --ignore-scripts) &
          (cd cli-releases && npm ci) &
          wait
      - name: Lint
        run: npm run lint
      - name: Format
        run: npm run format:check
